language: node_js
sudo: required
dist: trusty
before_script:
  - npm install
  - npm install -g bower
  - bower install
  - npm install -g karma-cli
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
script: npm run test
node_js:
  - "8"
addons:
  chrome: stable
